services:
  - type: web
    name: codelens-patient-api
    runtime: docker
    repo: https://github.com/AjayVegunta/codelens-patient-api
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codelens-patient-database
          property: connectionString
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

databases:
  - name: codelens-patient-database
    databaseName: codelens_patient
    user: codelens_patient_user
    plan: free
    region: singapore
    ipAllowList: []
    postgresMajorVersion: "16"

version: "1"
